### PR TITLE
fix linkage on msvc

### PR DESCRIPTION
**Pull request by steveklabnik**
this is not supposed to try something static unless the var is set

### CODE REVIEW

**Comment by sgrif** [comment]
Wait what? I thought msvc *only* did static?

**Comment by steveklabnik** [comment]
quoth @retep998

```text
15:27 < WindowsBunnyFiction> steveklabnik: Well technically it'll never try
                             static on windows msvc now :P
15:27 <@steveklabnik> heh
15:27 < WindowsBunnyFiction> steveklabnik: not that it really matters
15:28 < WindowsBunnyFiction> because kind=dylib just passes the library to
                             the linker, which works for both static and
                             dynamic libraries
> 15:29 < WindowsBunnyFiction> steveklabnik: Where it *would* matter is if they
                             actually had a #[link] attribute on the function
                             definitions, they'd be able to tie that to the
                             kind specified later on
```

**Comment by steveklabnik** [comment]
but the real issue here is that with `static`, it apparently looks for `pq`, _not_ `libpq`.

**Comment by retep998** [comment]
@sgrif msvc only links `.lib` libraries. However to actually pass a library to the linker you need `dylib`, not `static`. `static` causes rustc itself to do unspeakable things, finding the library via its own means and bundling it into the rlib.

**Comment by sgrif** [comment]
Ok. Well Appveyor says this is fine, so seems good. I was going to ask to add a branch for msvc and the static var being set, but it sounds like that's a bad idea.

**Pull request merged**
