### PR TITLE
Check PostgreSQL major version and add linking flags if needed

### PR DESCRIPTION
**Pull request by golddranks**
Fixing https://github.com/sgrif/pq-sys/issues/27

It might be that checking the version number is an overengineered solution. The extra linking flags aren't going to make the build fail on earlier versions, they are just not needed. What do you think? (I don't have any empirical evidence about whether linking unneeded stuff bloats the binary or not.)

### CODE REVIEW

**Comment by clux** [comment]
I know this is super old and ignored, but any chance this can be merged in? This is the last piece that is [needed to fix static builds](https://github.com/clux/muslrust/pull/98) provided users have `libpgport` and `libpgcommon` available.

**Comment by weiznich** [comment]
@clux If someone can provide an authoritative link to say the postgres documentation that this is the correct way to link libpq statically + goes through the comments in the linked issue we might be able to merge this. Otherwise this is unfortunately nothing that's high on my priority list, which means I personally won't spend much time working on it.

**Comment by golddranks** [comment]
The authoritative view, according to the mailing list, seems to be that you shouldn't ever link libpq statically.

**Comment by weiznich** [comment]
That's unfortunate, as this generally sounds like this would be a really brittle solution then. https://github.com/sgrif/pq-sys/issues/27#issuecomment-917248914 seems to have some information about potential duplicated symbols when linking both libraries. That might be important to add that as well here. 
And to just to double check that: The mailing list threads linked in the original issue are the most "official" thing we have on this, right?

**Comment by spruce** [comment]
Just for completeness this are the posts from the mailing list: 
Question: https://www.postgresql.org/message-id/CACS8yHKjrFOoTKKFOOted4d%2B16oN438DE0ydtp9y5QrxvcGp2w%40mail.gmail.com
Answer by the same author: https://www.postgresql.org/message-id/CACS8yHL0gbL3ECONrDygcBioTQBY%3DoVG-KGWB6%2BN7spG%2BeSMQw%40mail.gmail.com

**Comment by weiznich** [comment]
Closed in favor of #46

**Pull request closed without merging**
